language: android

jdk:
  - openjdk8

env:
  global:
    - GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m" # To limit memory use on CI and avoid OOMs
  - NODE_VERSION="12.7.0"
before_install:
  - nvm install $NODE_VERSION
  - npm install -g apollo-codegen@0.19.1
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools

install: ./gradlew build --stacktrace

script:
  - ./gradlew check --stacktrace


branches:
  only:
    - master

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
